line_bot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('taskmanagement/', include('taskmanagement.urls')),
    path('accounts/', include('allauth.urls')),     
    path('', include('login.urls')),             
    path('remindbot/', include("webapp.urls")),
]

login/urls.py
from django.urls import path, include
from . import views

# set the application namespace
# https://docs.djangoproject.com/en/2.0/intro/tutorial03/

app_name = 'login'

urlpatterns = [
    # ex: 
    path('', views.top, name='top'),
 ]

webapp/urls.py
from django.urls import path
from . import views

app_name = "webapp"

urlpatterns = [
    path('home/', views.home, name='home'),
    path('new/', views.TaskCreateView.as_view(), name='new'),
    path('edit/<int:pk>', views.TaskUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.TaskDeleteView.as_view(), name='delete'),
    path('pastTask/', views.pastTask, name='pastTask'),
    path('task_detail/<int:pk>', views.TaskDetailView.as_view(), name='task_detail'),
    path('new_pastTask/', views.PastTaskCreateView.as_view(), name='new_pastTask'),
]

webapp/models.py
from django.db import models

# Create your models here.

webapp/views.py
from django.shortcuts import render
from allauth.socialaccount.models import SocialAccount
from taskmanagement.models import Task
import logging
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.urls import reverse_lazy
from datetime import timedelta
from django.utils import timezone
from django import forms
from django.http import HttpResponse, HttpResponseRedirect

def home(request):
    # ログインしているとき
    if request.user.is_authenticated:
        social_accounts = SocialAccount.objects.filter(user=request.user)
        tasks = Task.objects.filter(user_ID=request.user, date__gte=timezone.now().date()).order_by('date', 'startTime')
        logging.debug(tasks)

        return render(request, "remindbot/home.html", {
            "social_accounts": social_accounts,
            "tasks": tasks,
        })

def pastTask(request):
    if request.user.is_authenticated:
        social_accounts = SocialAccount.objects.filter(user=request.user)
        tasks = Task.objects.filter(user_ID=request.user, date__lt=timezone.now().date()).order_by('date', 'startTime')
        logging.debug(tasks)

        return render(request, "remindbot/pastTask.html", {
            "social_accounts": social_accounts,
            "tasks": tasks,
        })

class TaskForm(forms.ModelForm):
    content = forms.CharField(label="タスク", widget=forms.TextInput(attrs={'class': 'custom-class'}))
    date = forms.DateField(label="日付", widget=forms.DateInput(attrs={'type': 'date'}))
    startTime = forms.TimeField(label="開始時刻", widget=forms.TimeInput(attrs={'type': 'time'}))
    endTime = forms.TimeField(label="終了時刻", widget=forms.TimeInput(attrs={'type': 'time'}))

    class Meta:
        model = Task
        fields = ['content', 'date', 'startTime', 'endTime']

class TaskCreateView(CreateView):
    """
    新規登録
    """

    form_class = TaskForm
    template_name = "remindbot/task_form.html"


    def form_valid(self, form):
        # ログインしているユーザーの情報を取得
        user_id = self.request.user

        # フォームのuser_IDにユーザーのIDを設定
        form.instance.user_ID = user_id

        # リマインドする日をフォームのデータがバリデーションを通過した後のdateを取得する
        remind_date = form.cleaned_data['date'] - timedelta(days=1)

        # 過去の日付が入力された場合
        if remind_date < timezone.now().date():
            form.add_error('date', '過去の日付は指定できません')
            return self.form_invalid(form)

        # フォームのremind_dateに設定
        form.instance.remind_date = remind_date

        # フォームが有効なら保存
        return super().form_valid(form)


class TaskUpdateView(UpdateView):
    """
    編集
    """

    model = Task

    # 更新項目
    # fields = ['content', 'date', 'startTime', 'endTime']
    form_class = TaskForm

    # テンプレートファイル名の接尾辞の指定
    template_name = 'remindbot/update_form.html'


class TaskDeleteView(DeleteView):
    """
    削除
    """

    model = Task

    template_name = 'remindbot/task_confirm_delete.html'

    # 削除完了後のリダイレクト先
    success_url = reverse_lazy('webapp:home')

class TaskDetailView(DetailView):
    model = Task
    template_name = 'remindbot/task_detail.html'
    context_object_name = 'task'

class PastTaskCreateView(CreateView):
    """
    新規登録
    """

    form_class = TaskForm
    template_name = "remindbot/past_task_form.html"


    def form_valid(self, form):
        # ログインしているユーザーの情報を取得
        user_id = self.request.user

        # フォームのuser_IDにユーザーのIDを設定
        form.instance.user_ID = user_id

        # リマインドする日をフォームのデータがバリデーションを通過した後のdateを取得する
        remind_date = form.cleaned_data['date'] - timedelta(days=1)

        # 過去の日付が入力された場合
        if remind_date > timezone.now().date():
            form.add_error('date', '未来の日付は指定できません')
            return self.form_invalid(form)

        # フォームのremind_dateに設定
        form.instance.remind_date = remind_date

        # フォームが有効なら保存
        return super().form_valid(form)

webapp/templates/remindbot/home.html
{% extends "layouts/base.html" %}

{% load account %}
{% load allauth account %}

{% block body %}
    {% if social_accounts %}

        {% for account in social_accounts %}
            <h1>ようこそ，{{ account.extra_data.displayName }}さん</h1>
        {% endfor %}

        <a href="{% url 'webapp:new' %}">新規登録</a>

        {% for task in tasks %}
        <ul>
            <tr>
                <td>{{ task.content }}</td>
                <td>{{ task.date }}</td>
                <td>
                    <a href="{% url 'webapp:edit' pk=task.pk %}">編集</a>
                    <a href="{% url 'webapp:delete' pk=task.pk %}">削除</a>
                </td>
            </tr>
        </ul>
        {% endfor %}
                            
            
    {% else %}



    {% endif %}
{% endblock body %}

webapp/templates/remindbot/pastTask.html
{% extends "layouts/base.html" %}

{% load static %}
{% load account %}
{% load allauth account %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'webapp/home.css' %}">
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var rows = document.querySelectorAll('tr[data-href]');
            rows.forEach(function(row) {
                row.addEventListener('click', function() {
                    window.location.href = row.dataset.href;
                });
            });
        });
    </script>
{% endblock extra_head %}

{% block body %}
    {% if social_accounts %}

        <div class="container text-center">
            <div class="row align-items-start">
            <div class="col-auto me-auto mt-4 mb-4">
                {% for account in social_accounts %}
                    <h1 class="fs-2">過去のタスク</h1>
                {% endfor %}
            </div>
            <div class="col-auto mt-4">
                <a class="btn btn-outline-secondary" href="{% url 'webapp:new_pastTask' %}" role="button">過去のタスクを追加</a>
            </div>
            </div>
        </div>
        
        <table class="table table-hover">
            <thead>
              <tr class="table-secondary">
                <th scope="col">日付</th>
                <th scope="col">タスク内容</th>
                <th scope="col">開始時刻</th>
                <th scope="col">終了時刻</th>
                <th scope="col"></th>
                <th scope="col"></th>
              </tr>
            </thead>

            {% for task in tasks %}
            <tbody>
              <tr data-href="{% url 'webapp:task_detail' pk=task.pk %}">
                <td>{{ task.date }}</td>
                <td>{{ task.content|truncatechars:10 }}</td>
                <td>{{ task.startTime }}</td>
                <td>{{ task.endTime }}</td>
                <td>
                    <a class="btn btn-outline-primary" href="{% url 'webapp:edit' pk=task.pk %}" role="button">
                        <img src="{% static 'svg/pencil-square.svg' %}" alt="EditIcon">
                    </a>
                </td>
                <td>
                    <a class="btn btn-outline-danger" href="{% url 'webapp:delete' pk=task.pk %}" role="button">
                        <img src="{% static 'svg/trash3.svg' %}" alt="TrashIcon">
                    </a>
                </td>
              </tr>
            </tbody>
            {% endfor %}

        </table>        

    {% else %}

    {% endif %}
{% endblock body %}

webapp/templates/remindbot/past_task_form.html
{% extends "layouts/base.html" %}

{% block body %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-success text-white">
                    <h1 class="card-title fs-3 mt-2 d-flex justify-content-center">登録フォーム</h1>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                    
                </div>
                <div class="card-footer d-flex">
                    <a href="{% url 'webapp:pastTask' %}" class="btn btn-secondary">戻る</a>
                    <input type="submit" value="登録" class="btn btn-success ms-auto">
                </div>

                    </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

webapp/templates/remindbot/task_confirm_delete.html
{% extends "layouts/base.html" %}

{% block body %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-danger text-white">
                    <h1 class="card-title fs-3 mt-2 d-flex justify-content-center">タスク削除</h1>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p class="card-text">以下のタスクを削除してもよろしいですか？</p>
                        <p class="card-text">{{ task.content }}</p>
                        {{ form }}          
                </div>
                <div class="card-footer d-flex">
                    <a href="{% url 'webapp:home' %}" class="btn btn-secondary">戻る</a>
                    <input type="submit" value="削除" class="btn btn-danger ms-auto">
                </div>
                
                    </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}

webapp/templates/remindbot/task_detail.html
{% extends "layouts/base.html" %}

{% block body %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-info text-white">
                    <h1 class="card-title fs-3 mt-2 d-flex justify-content-center">タスク詳細</h1>
                </div>
                <div class="card-body">
                    <p>{{ task.date }}</p>
                    <p>{{ task.content }}</p>
                    <p>開始時刻: {{ task.startTime }}</p>
                    <p>終了時刻: {{ task.endTime }}</p>
                </div>
                <div class="card-footer d-flex">
                    <a href="{% url 'webapp:home' %}" class="btn btn-secondary">戻る</a>
                </div>
                
                    
            </div>
        </div>
    </div>
</div>
{% endblock body %}

webapp/templates/remindbot/task_form.html
<h1>新規登録</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <a href="{% url 'webapp:home' %}">戻る</a>
    <input type="submit" value="登録">
</form>

webapp/templates/remindbot/update_form.html
{% extends "layouts/base.html" %}

{% block body %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h1 class="card-title fs-3 mt-2 d-flex justify-content-center">編集フォーム</h1>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                    
                </div>
                <div class="card-footer d-flex">
                    <a href="{% url 'webapp:home' %}" class="btn btn-secondary">戻る</a>
                    <input type="submit" value="編集" class="btn btn-primary ms-auto">
                </div>

                    </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %}